# Every process file becomes a component
#
# Debug inputs
#       application_folder: "bw5doctest"
#              application: "EMSInteraction"
#         bw5_project_name: "EMSInteraction"
#              bw5_project: {"fixedChildren":"AESchemas","projectProperties":{"property":[{"@_key":"ae.palette.SOAPpalette.version","@_value":"5.16.1"},{"@_key":"ae.palette.parsepalette.version","@_value":"5.16.1"},{"@_key":"turbo.palette.version","@_value":"5.6.1"},{"@_key":"ae.palette.Mail.palette.version","@_value":"5.16.1"},{"@_key":"ae.palette.Policy.version","@_value":"5.16.1"},{"@_key":"ae.process.palette.version","@_value":"5.16.1"},{"@_key":"ae.repo.palette.version","@_value":"5.3.0"},{"@_key":"httppalette.httpplugins.version","@_value":"5.16.1"},{"@_key":"ae.aepalette.ae.palette.version","@_value":"5.16.1"},{"@_key":"palette.generalpalette.version","@_value":"5.3.0"},{"@_key":"ae.palette.GeneralPalette.version","@_value":"5.16.1"},{"@_key":"service.palette.version","@_value":"5.16.1"},{"@_key":"wadlresource.palette.version","@_value":"1.0.0.00"},{"@_key":"ae.palette.transaction.palette.version","@_value":"5.16.1"},{"@_key":"ae.palette.JMS.palette.version","@_value":"5.16.1"},{"@_key":"wsdlresource.palette.version","@_value":"5.16.1"},{"@_key":"palette.ae.metadata.version","@_value":"5.3.0"},{"@_key":"ae.palette.Filepalette.version","@_value":"5.16.1"},{"@_key":"ae.palette.jrmi.palette.version","@_value":"5.16.1"},{"@_key":"aa.adapteradministrator.palette.version","@_value":"5.3.0"},{"@_key":"ae.palette.java.palette.version","@_value":"5.16.1"},{"@_key":"ae.designerapp.version","@_value":"5.13.0.10"},{"@_key":"ae.pallette.tcp.pallette.version","@_value":"5.16.1"},{"@_key":"ae.palette.xml.palette.version","@_value":"5.16.1"},{"@_key":"ae.palette.jsonpalette.version","@_value":"2.1.0.71"},{"@_key":"ae.palette.JDBCpalette.version","@_value":"5.16.1"},{"@_key":"ae.palette.rvpalette.version","@_value":"5.16.1"},{"@_key":"ae.palette.FTPpalette.version","@_value":"5.16.1"},{"@_key":"projectName","@_value":"EMSInteraction"}]},"@_resourceType":"ae.rootfolder","@_name":"EMSInteraction","@_propLocks":"","@_allowUserToChangeIcon":"false","@_sortContents":"false","@_acceptsResources":"true","@_allowDuplicates":"false"}
#         bw5_project_name: "EMSInteraction"
#  bw5_project_description: 
#                  repoUrl: "github.com?owner=mcommiss-tibco&repo=bw5doctest"
#                    owner: "group:default/tibco-self-service"
#                api_files: []
#          api_files_names: []
#                 db_files: []
#           db_files_names: []
#            process_files: ["Processes/ServiceProvider/StoreOrder.process","Processes/ServiceProvider/ReceiveJMSRequest.process","Processes/ServiceConsumer/SendOrder.process","Processes/ServiceConsumer/OrderTrigger.process","Processes/ServiceConsumer/GenerateOrder.process"]
#      process_files_names: ["StoreOrder.process","ReceiveJMSRequest.process","SendOrder.process","OrderTrigger.process","GenerateOrder.process"]


apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    name: EMSInteraction
    description: 
    tags:
      - bw5-project
    links:
      - title: Business Works 5
        url: https://docs.tibco.com/products/tibco-activematrix-businessworks-5-13-0
    annotations:
        github.com/project-slug: https://github.com/mcommiss-tibco/bw5doctest
spec:
    type: service
    lifecycle: production
    owner: group:default/tibco-imported
    system: bw5-projects
---    
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
#    name: StoreOrder_BW5_PROCESS
    name: BW5_PROCESS_StoreOrder
    description: StoreOrder.process
    tags:
      - bw5-process
    links:
      - title: Business Works 5
        url: https://docs.tibco.com/products/tibco-activematrix-businessworks-5-13-0
    annotations:
      github.com/project-slug: https://github.com/mcommiss-tibco/bw5doctest
spec:
    type: bw-5-process
    lifecycle: production
    owner: group:default/tibco-self-service
    subcomponentOf: component:default/EMSInteraction
    # system: EMSInteraction
---    
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
#    name: ReceiveJMSRequest_BW5_PROCESS
    name: BW5_PROCESS_ReceiveJMSRequest
    description: ReceiveJMSRequest.process
    tags:
      - bw5-process
    links:
      - title: Business Works 5
        url: https://docs.tibco.com/products/tibco-activematrix-businessworks-5-13-0
    annotations:
      github.com/project-slug: https://github.com/mcommiss-tibco/bw5doctest
spec:
    type: bw-5-process
    lifecycle: production
    owner: group:default/tibco-self-service
    subcomponentOf: component:default/EMSInteraction
    # system: EMSInteraction
---    
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
#    name: SendOrder_BW5_PROCESS
    name: BW5_PROCESS_SendOrder
    description: SendOrder.process
    tags:
      - bw5-process
    links:
      - title: Business Works 5
        url: https://docs.tibco.com/products/tibco-activematrix-businessworks-5-13-0
    annotations:
      github.com/project-slug: https://github.com/mcommiss-tibco/bw5doctest
spec:
    type: bw-5-process
    lifecycle: production
    owner: group:default/tibco-self-service
    subcomponentOf: component:default/EMSInteraction
    # system: EMSInteraction
---    
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
#    name: OrderTrigger_BW5_PROCESS
    name: BW5_PROCESS_OrderTrigger
    description: OrderTrigger.process
    tags:
      - bw5-process
    links:
      - title: Business Works 5
        url: https://docs.tibco.com/products/tibco-activematrix-businessworks-5-13-0
    annotations:
      github.com/project-slug: https://github.com/mcommiss-tibco/bw5doctest
spec:
    type: bw-5-process
    lifecycle: production
    owner: group:default/tibco-self-service
    subcomponentOf: component:default/EMSInteraction
    # system: EMSInteraction
---    
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
#    name: GenerateOrder_BW5_PROCESS
    name: BW5_PROCESS_GenerateOrder
    description: GenerateOrder.process
    tags:
      - bw5-process
    links:
      - title: Business Works 5
        url: https://docs.tibco.com/products/tibco-activematrix-businessworks-5-13-0
    annotations:
      github.com/project-slug: https://github.com/mcommiss-tibco/bw5doctest
spec:
    type: bw-5-process
    lifecycle: production
    owner: group:default/tibco-self-service
    subcomponentOf: component:default/EMSInteraction
    # system: EMSInteraction   

